[dev]
targetPort = 8080

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301
  force = true

[[redirects]]
  from = "/a-propos"
  to = "/#about"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio"
  to = "/#testimonials"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 